### ISSUE TITLE
Interface event definitions converted as "private"

### ISSUE THREAD

**Issue by elGuille-info** [paul1956/CSharpToVB#81]
On interface definition the modifiers is not used.

``` 
public interface IDrawingObject
{
    event EventHandler OnDraw;
}
```

Is converted to:

``` 
Public Interface IDrawingObject
    Private Event OnDraw As EventHandler
End Interface
```

And should be:

```
Public Interface IDrawingObject
    Event OnDraw As EventHandler
End Interface
```

Guillermo.

P.S.
The whole sample (on MS docs) 
[How to implement interface events (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/events/how-to-implement-interface-events)

is not converted on the last version 5.0.4.0.
Throw that exception (show in te converted panel):
```
----- Exception 1 Of 1 -----
System.InvalidOperationException: The program location VisitEventDeclaration line 453 is thought to be unreachable.
   at CSharpToVBConverter.CSharpToVBVisitors.CSharpConverter.NodesVisitor.VisitEventDeclaration(EventDeclarationSyntax node) in E:\gsCodigo_00\Visual Studio\CSharpToVB_git\CSharpToVB\CodeConverter\CSharpToVBConverter\CSharpToVBVisitors\DeclarationVisitor.vb:line 478
   at Microsoft.CodeAnalysis.CSharp.Syntax.EventDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at CSharpToVBConverter.CSharpToVBVisitors.CSharpConverter.NodesVisitor.VisitClassDeclaration(ClassDeclarationSyntax node) in E:\gsCodigo_00\Visual Studio\CSharpToVB_git\CSharpToVB\CodeConverter\CSharpToVBConverter\CSharpToVBVisitors\NamespaceVisitor.vb:line 338
   at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at CSharpToVBConverter.CSharpToVBVisitors.CSharpConverter.NodesVisitor.VisitNamespaceDeclaration(NamespaceDeclarationSyntax node) in E:\gsCodigo_00\Visual Studio\CSharpToVB_git\CSharpToVB\CodeConverter\CSharpToVBConverter\CSharpToVBVisitors\NamespaceVisitor.vb:line 770
   at Microsoft.CodeAnalysis.CSharp.Syntax.NamespaceDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at CSharpToVBConverter.CSharpToVBVisitors.CSharpConverter.NodesVisitor.VisitCompilationUnit(CompilationUnitSyntax node) in E:\gsCodigo_00\Visual Studio\CSharpToVB_git\CSharpToVB\CodeConverter\CSharpToVBConverter\CSharpToVBVisitors\NodesVisitor.vb:line 157
   at Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at LanguageSyntaxNodeExtensions.DoConversion(CSharpSyntaxNode sourceTree, SemanticModel pSemanticModel, DefaultVbOptions defaultVbOptions, Boolean skipAutoGenerated, Boolean isProjectConversion, Action`1 reportException, IProgress`1 progress, List`1 globalSymbols, CancellationToken cancelToken) in E:\gsCodigo_00\Visual Studio\CSharpToVB_git\CSharpToVB\CodeConverter\Extensions\LanguageSyntaxNodeExtensions.vb:line 416
   at DoConversion.ConvertInputRequest(ConvertRequest requestToConvert, DefaultVbOptions defaultVbOptions, List`1 csPreprocessorSymbols, List`1 vbPreprocessorSymbols, MetadataReference[] optionalReferences, Action`1 reportException, IProgress`1 mProgress) in E:\gsCodigo_00\Visual Studio\CSharpToVB_git\CSharpToVB\CodeConverter\Utilities\DoConversion.vb:line 82

```

But is converted (without errors) in version 5.0.3.2 with the same issue.

**Comment by paul1956** [comment]
@elGuille-info both issues fixed in 5.0.6.0/5.0.2.4 with update to .Net 6.0
